# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://mo7amed3umr.github.io
baseurl: /moomar/
title: Mohamed Omar
author: Mohamed Omar
description: Personal blog and resume
avatar: profile.png
email: mohamed.kader99@email.com
github: mo7amed3umr # username
twitter: abuu3umr
linkedin: mohamed omar
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
